[env]
OPENCV_INCLUDE_PATHS = "C:\\opencv\\build\\include"
OPENCV_LINK_PATHS = "C:\\opencv\\build\\x64\\vc16\\lib"
OPENCV_LINK_LIBS = "opencv_world4120"
# OpenCVのビルドでclangを使わない設定
OPENCV_DISABLE_PROBES = "1"

[build]
# Windows向けのリンカー設定
rustflags = ["-L", "C:\\opencv\\build\\x64\\vc16\\lib"]
